language: scala

scala:
  - 2.10.4
  - 2.11.4

jdk:
  - oraclejdk7

branches:
    - specs2-three

script: sbt -sbt-version 0.13.7-RC2 -scala-version $TRAVIS_SCALA_VERSION 'test-only -- -exclude unstable -xonly; coveralls'
